
-- Criar usuários de teste para o sistema
-- Inserir usuário admin
INSERT INTO auth.users (
  id,
  instance_id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  confirmation_sent_at,
  recovery_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone_confirmed_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES 
(
  gen_random_uuid(),
  '00000000-0000-0000-0000-000000000000',
  'authenticated',
  'authenticated',
  'admin@sistema.com',
  '$2a$10$XTtYZQ8Y8Y8Y8Y8Y8Y8Y8O7Q8Y8Y8Y8Y8Y8Y8Y8Y8Y8Y8Y8Y8Y8Y8Y8Y8',
  NOW(),
  NOW(),
  NOW(),
  NOW(),
  '{"provider":"email","providers":["email"]}',
  '{"name":"Admin Sistema","role":"admin"}',
  FALSE,
  NOW(),
  NOW(),
  NULL,
  0,
  NULL,
  NOW(),
  FALSE,
  NULL
);

-- Inserir usuário lojista
INSERT INTO auth.users (
  id,
  instance_id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  confirmation_sent_at,
  recovery_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone_confirmed_at,
  email_change_confirm_status,
  banned_until,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES 
(
  gen_random_uuid(),
  '00000000-0000-0000-0000-000000000000',
  'authenticated',
  'authenticated',
  'joao@pizzaria.com',
  '$2a$10$XTtYZQ8Y8Y8Y8Y8Y8Y8Y8O7Q8Y8Y8Y8Y8Y8Y8Y8Y8Y8Y8Y8Y8Y8Y8Y8Y8',
  NOW(),
  NOW(),
  NOW(),
  NOW(),
  '{"provider":"email","providers":["email"]}',
  '{"name":"João Pizzaria","role":"lojista"}',
  FALSE,
  NOW(),
  NOW(),
  NULL,
  0,
  NULL,
  NOW(),
  FALSE,
  NULL
);
